import type { LucideIcon } from "lucide-react";
import {
  Anchor,
  BadgePercent,
  Bike,
  Building2,
  BusFront,
  Bus,
  Camera,
  Car,
  Caravan,
  Castle,
  CircleHelp,
  Compass,
  Dumbbell,
  Gem,
  Gift,
  GraduationCap,
  FerrisWheel,
  Flame,
  Fish,
  Globe,
  HeartPulse,
  Hotel,
  Lamp,
  Leaf,
  Map,
  MapPin,
  Medal,
  MountainSnow,
  MoreHorizontal,
  Palette,
  PlaneTakeoff,
  Rocket,
  ShieldPlus,
  ShipWheel,
  ShoppingCart,
  Snowflake,
  Sunset,
  TentTree,
  TrainFront,
  TreePalm,
  Trophy,
  Waves,
  Mountain,
  PartyPopper,
  Plane,
  Route,
  Sailboat,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Ticket,
  UtensilsCrossed,
  Wind,
} from "lucide-react";

export interface CategoryIconOption {
  key: string;
  label: string;
  group: string;
  keywords: string[];
}

export const CATEGORY_ICON_OPTIONS: CategoryIconOption[] = [
  { key: "route", label: "Route", group: "Travel", keywords: ["tour", "path", "travel", "road"] },
  { key: "map", label: "Map", group: "Travel", keywords: ["map", "location", "travel"] },
  { key: "compass", label: "Compass", group: "Travel", keywords: ["direction", "travel", "explore"] },
  { key: "map-pin", label: "Map Pin", group: "Travel", keywords: ["location", "pin", "place"] },
  { key: "plane", label: "Plane", group: "Travel", keywords: ["airport", "flight", "air"] },
  { key: "plane-takeoff", label: "Plane Takeoff", group: "Travel", keywords: ["flight", "departure", "airport"] },
  { key: "train-front", label: "Train Front", group: "Travel", keywords: ["train", "rail", "transport"] },
  { key: "castle", label: "Castle", group: "Travel", keywords: ["history", "heritage", "landmark"] },
  { key: "tent-tree", label: "Tent Tree", group: "Travel", keywords: ["camp", "nature", "trip"] },
  { key: "car", label: "Car", group: "Transport", keywords: ["transfer", "vehicle", "ride"] },
  { key: "bus", label: "Bus", group: "Transport", keywords: ["shuttle", "group", "transport"] },
  { key: "bus-front", label: "Bus Front", group: "Transport", keywords: ["shuttle", "city", "transport"] },
  { key: "bike", label: "Bike", group: "Transport", keywords: ["motor", "activity", "ride"] },
  { key: "sailboat", label: "Sailboat", group: "Transport", keywords: ["boat", "sea", "trip"] },
  { key: "caravan", label: "Caravan", group: "Transport", keywords: ["roadtrip", "camper", "vehicle"] },
  { key: "ship-wheel", label: "Ship Wheel", group: "Transport", keywords: ["captain", "sea", "navigation"] },
  { key: "anchor", label: "Anchor", group: "Transport", keywords: ["harbor", "boat", "sea"] },
  { key: "wind", label: "Wind", group: "Nature", keywords: ["balloon", "air", "sky"] },
  { key: "mountain", label: "Mountain", group: "Nature", keywords: ["landscape", "nature", "outdoor"] },
  { key: "mountain-snow", label: "Mountain Snow", group: "Nature", keywords: ["winter", "ski", "alpine"] },
  { key: "waves", label: "Waves", group: "Nature", keywords: ["water", "beach", "sea"] },
  { key: "tree-palm", label: "Tree Palm", group: "Nature", keywords: ["beach", "tropical", "holiday"] },
  { key: "leaf", label: "Leaf", group: "Nature", keywords: ["eco", "green", "nature"] },
  { key: "sunset", label: "Sunset", group: "Nature", keywords: ["sun", "evening", "landscape"] },
  { key: "snowflake", label: "Snowflake", group: "Nature", keywords: ["winter", "cold", "season"] },
  { key: "fish", label: "Fish", group: "Nature", keywords: ["sea", "underwater", "marine"] },
  { key: "flame", label: "Flame", group: "Nature", keywords: ["adventure", "energy"] },
  { key: "sparkles", label: "Sparkles", group: "Experience", keywords: ["premium", "special", "vip"] },
  { key: "ferris-wheel", label: "Ferris Wheel", group: "Experience", keywords: ["fun", "activity", "park"] },
  { key: "party-popper", label: "Party Popper", group: "Experience", keywords: ["event", "celebration"] },
  { key: "camera", label: "Camera", group: "Experience", keywords: ["photo", "gallery", "media"] },
  { key: "trophy", label: "Trophy", group: "Experience", keywords: ["winner", "event", "achievement"] },
  { key: "medal", label: "Medal", group: "Experience", keywords: ["success", "award", "event"] },
  { key: "gift", label: "Gift", group: "Experience", keywords: ["surprise", "package", "special"] },
  { key: "rocket", label: "Rocket", group: "Experience", keywords: ["speed", "adventure", "launch"] },
  { key: "gem", label: "Gem", group: "Experience", keywords: ["luxury", "vip", "premium"] },
  { key: "graduation-cap", label: "Graduation Cap", group: "Experience", keywords: ["education", "workshop", "learning"] },
  { key: "ticket", label: "Ticket", group: "Commerce", keywords: ["booking", "reservation", "entry"] },
  { key: "shopping-bag", label: "Shopping Bag", group: "Commerce", keywords: ["shop", "store", "product"] },
  { key: "shopping-cart", label: "Shopping Cart", group: "Commerce", keywords: ["buy", "market", "order"] },
  { key: "badge-percent", label: "Badge Percent", group: "Commerce", keywords: ["sale", "discount", "offer"] },
  { key: "building-2", label: "Building 2", group: "Commerce", keywords: ["business", "company", "office"] },
  { key: "palette", label: "Palette", group: "Commerce", keywords: ["design", "creative", "art"] },
  { key: "utensils", label: "Utensils", group: "Service", keywords: ["food", "restaurant", "meal"] },
  { key: "hotel", label: "Hotel", group: "Service", keywords: ["accommodation", "room"] },
  { key: "shield-check", label: "Shield Check", group: "Service", keywords: ["safe", "approved", "quality"] },
  { key: "shield-plus", label: "Shield Plus", group: "Service", keywords: ["security", "protection", "care"] },
  { key: "heart-pulse", label: "Heart Pulse", group: "Service", keywords: ["health", "wellness"] },
  { key: "dumbbell", label: "Dumbbell", group: "Service", keywords: ["fitness", "gym", "sport"] },
  { key: "lamp", label: "Lamp", group: "Service", keywords: ["comfort", "home", "service"] },
  { key: "waves-ladder", label: "Pool", group: "Service", keywords: ["pool", "swim", "water"] },
  { key: "globe", label: "Globe", group: "Service", keywords: ["international", "global"] },
  { key: "more-horizontal", label: "More Horizontal", group: "Other", keywords: ["other", "misc"] },
];

const iconMap: Record<string, LucideIcon> = {
  route: Route,
  map: Map,
  compass: Compass,
  "map-pin": MapPin,
  plane: Plane,
  "plane-takeoff": PlaneTakeoff,
  "train-front": TrainFront,
  castle: Castle,
  "tent-tree": TentTree,
  car: Car,
  bus: Bus,
  "bus-front": BusFront,
  bike: Bike,
  sailboat: Sailboat,
  caravan: Caravan,
  "ship-wheel": ShipWheel,
  anchor: Anchor,
  wind: Wind,
  mountain: Mountain,
  "mountain-snow": MountainSnow,
  waves: Waves,
  "tree-palm": TreePalm,
  leaf: Leaf,
  sunset: Sunset,
  snowflake: Snowflake,
  fish: Fish,
  flame: Flame,
  sparkles: Sparkles,
  "ferris-wheel": FerrisWheel,
  "party-popper": PartyPopper,
  camera: Camera,
  trophy: Trophy,
  medal: Medal,
  gift: Gift,
  rocket: Rocket,
  gem: Gem,
  "graduation-cap": GraduationCap,
  ticket: Ticket,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  "badge-percent": BadgePercent,
  "building-2": Building2,
  palette: Palette,
  utensils: UtensilsCrossed,
  hotel: Hotel,
  "shield-check": ShieldCheck,
  "shield-plus": ShieldPlus,
  "heart-pulse": HeartPulse,
  dumbbell: Dumbbell,
  lamp: Lamp,
  "waves-ladder": Waves,
  globe: Globe,
  "more-horizontal": MoreHorizontal,
};

export const getCategoryIcon = (iconKey: string) => {
  return iconMap[iconKey] || CircleHelp;
};

export const getCategoryIconOption = (iconKey: string) => {
  return CATEGORY_ICON_OPTIONS.find((option) => option.key === iconKey);
};


